Fix log4j error
currently you get this:

Status: Downloaded newer image for pmoust/s3s3mirror:latest
log4j:ERROR Could not parse url [file:target/conf/log4j.xml].
java.io.FileNotFoundException: target/conf/log4j.xml (No such file or directory)

this is because the s3s3mirror.sh script is using a relative path to find the log4j config
if you make the checked out repo the working directory in the docker file then this problem goes away and output logs properly